# Generated by Django 5.1.3 on 2024-12-03 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='arsenalero',
        ),
        migrations.AddField(
            model_name='schedule',
            name='arsenero',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AUXILIAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arsenero_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='anesthetist',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='anesthetist_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='nurse',
            field=models.ForeignKey(limit_choices_to={'role': 'NURSE'}, on_delete=django.db.models.deletion.CASCADE, related_name='nurse_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pabellon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduling.pabellon'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pabellonero',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AUXILIAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pabellonero_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='patient_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='surgeon',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tecnico_anestesia',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'AUXILIAR'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_anestesia_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
