# Generated by Django 5.1.3 on 2024-12-03 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pabellon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('DESOCUPADO', 'Desocupado'), ('LIMPIEZA', 'Limpieza')], default='DESOCUPADO', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='pabellon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scheduling.pabellon'),
        ),
    ]
