# Generated by Django 5.1.3 on 2024-12-03 05:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0002_remove_schedule_arsenalero_schedule_arsenero_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='arsenero',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'ARSENALERO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='arsenero_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='pabellonero',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'PABELLONERO'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pabellonero_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='tecnico_anestesia',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'TECNICO_ANESTESIA'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tecnico_anestesia_schedules', to=settings.AUTH_USER_MODEL),
        ),
    ]
